---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids:
    - ci-testing
  instance_type: c3.xlarge
  tags:
    Env: public
    Type: test
  iam_profile_name: test-ec2dnsserver

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  client_rb:
    environment: 'test'
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-7d7d7c17

suites:
  - name: default
    driver_config:
      network:
        - - private_network
          - ip: '192.168.33.11'
    run_list:
      - recipe[ec2ohaihints::default]
      - recipe[et_hostname::default]
      - recipe[test-tools::default]
      - recipe[mock-ec2::default]
      - recipe[ec2dnsserver::default]
      - recipe[test-data::default]
      - recipe[shinken::default]
      - recipe[shinken::webui]
      - recipe[shinken::broker]
    attributes:
      shinken:
        install_type: source
      et_hostname:
        addl_hosts_entries:
          - '192.168.33.11 test-dns.local'
      ec2dnsserver:
        contact_email: 'hostmaster@yourdomain.local'
        recursion_clients:
          - 192.168.19.0/24
        avoid_subnets: []
        zones:
          vagrantup.com: {}
          test-dns.local:
            stub: true
            ns_zone: local
            static_records:
              value: 192.168.33.11
              type: A
