language: ruby
cache:
  directories:
  - "$HOME/.berkshelf"
rvm: 2.3
addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk
before_install:
- mkdir ~/.chef
- echo 'node_name "trubot"' >> ~/.chef/knife.rb
install:
- eval "$(chef shell-init bash)"
- chef gem install kitchen-ec2 kitchen-sync
- berks
before_script:
- chef --version
- rubocop --version
- foodcritic --version
script:
- rubocop
- foodcritic .
- chef exec rspec
- kitchen test ${SUITE} -d always
# - kitchen test -d always
env:
  matrix:
  - SUITE: default
